/*
 * Copyright (c) 2008-2009, 3Di, Inc. (http://3di.jp/) and contributors.
 * See CONTRIBUTORS.TXT for a full list of copyright holders.
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of 3Di, Inc., nor the name of the 3Di Viewer
 *       "Rei" project, nor the names of its contributors may be used to
 *       endorse or promote products derived from this software without
 *       specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY 3Di, Inc. AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL 3Di, Inc. OR THE
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.4927
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenViewer
{

using System;


    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DialogText
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogText()
        {
        }

        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenViewer.DialogText", typeof(DialogText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   An incoming call was received. Do you accept it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AcceptRingingMessage
        {
            get
            {
                return ResourceManager.GetString("AcceptRingingMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Cache に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cache
        {
            get
            {
                return ResourceManager.GetString("Cache", resourceCulture);
            }
        }

        /// <summary>
        ///   Please restart your browser. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CacheDeleteConfirm
        {
            get
            {
                return ResourceManager.GetString("CacheDeleteConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Please restart your browser. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CacheDeleteMessage
        {
            get
            {
                return ResourceManager.GetString("CacheDeleteMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   For faster displaying, some data is
        ///stored on your machine. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CacheInformationMessage
        {
            get
            {
                return ResourceManager.GetString("CacheInformationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Cache (MB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CacheUnitMessage
        {
            get
            {
                return ResourceManager.GetString("CacheUnitMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Chat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Chat
        {
            get
            {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }

        /// <summary>
        ///   Debug に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Debug
        {
            get
            {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }

        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Your environment does not support sky displaying. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisabledSkyShader
        {
            get
            {
                return ResourceManager.GetString("DisabledSkyShader", resourceCulture);
            }
        }

        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EN
        {
            get
            {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }

        /// <summary>
        ///   Network error
        ///You have been disconnected from the server.
        ///Please log out. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorConnectionMessage
        {
            get
            {
                return ResourceManager.GetString("ErrorConnectionMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Restart the viewer? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorFinalMessageme00
        {
            get
            {
                return ResourceManager.GetString("ErrorFinalMessageme00", resourceCulture);
            }
        }

        /// <summary>
        ///   The viewer is restarted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorFinalMessageme01
        {
            get
            {
                return ResourceManager.GetString("ErrorFinalMessageme01", resourceCulture);
            }
        }

        /// <summary>
        ///   Creating graphics device failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorGraphicDriverCaption
        {
            get
            {
                return ResourceManager.GetString("ErrorGraphicDriverCaption", resourceCulture);
            }
        }

        /// <summary>
        ///   Please check if your graphics card&apos;s driver is the latest version and update if necessary. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorGraphicDriverMessage
        {
            get
            {
                return ResourceManager.GetString("ErrorGraphicDriverMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Login error.
        /// 
        ///Please check your
        ///username and password
        ///and try logging in in a short while. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorLoginMessageme00
        {
            get
            {
                return ResourceManager.GetString("ErrorLoginMessageme00", resourceCulture);
            }
        }

        /// <summary>
        ///   Login error
        ///You seem to be already logged in.
        ///Please try again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorLoginMessageme01
        {
            get
            {
                return ResourceManager.GetString("ErrorLoginMessageme01", resourceCulture);
            }
        }

        /// <summary>
        ///   Teleport has failed.
        ///Please log in again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorTeleportMessage
        {
            get
            {
                return ResourceManager.GetString("ErrorTeleportMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Firstname に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Firstname
        {
            get
            {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }

        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General
        {
            get
            {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }

        /// <summary>
        ///   Graphics に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Graphics
        {
            get
            {
                return ResourceManager.GetString("Graphics", resourceCulture);
            }
        }

        /// <summary>
        ///   High に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string High
        {
            get
            {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }

        /// <summary>
        ///   Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Information
        {
            get
            {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }

        /// <summary>
        ///   Japanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JP
        {
            get
            {
                return ResourceManager.GetString("JP", resourceCulture);
            }
        }

        /// <summary>
        ///   Lastname に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Lastname
        {
            get
            {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }

        /// <summary>
        ///   Locale に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Locale
        {
            get
            {
                return ResourceManager.GetString("Locale", resourceCulture);
            }
        }

        /// <summary>
        ///   Login に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Login
        {
            get
            {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }

        /// <summary>
        ///   Low に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Low
        {
            get
            {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }

        /// <summary>
        ///   DISCONNECTED に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuDisconnectMessage
        {
            get
            {
                return ResourceManager.GetString("MenuDisconnectMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Pos x: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuPositionMessage
        {
            get
            {
                return ResourceManager.GetString("MenuPositionMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Region: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuRegionMessage
        {
            get
            {
                return ResourceManager.GetString("MenuRegionMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Message に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageWindowCaption
        {
            get
            {
                return ResourceManager.GetString("MessageWindowCaption", resourceCulture);
            }
        }

        /// <summary>
        ///   Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        /// <summary>
        ///   The specified port is not usable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PortError
        {
            get
            {
                return ResourceManager.GetString("PortError", resourceCulture);
            }
        }

        /// <summary>
        ///   Region Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RegionName
        {
            get
            {
                return ResourceManager.GetString("RegionName", resourceCulture);
            }
        }

        /// <summary>
        ///   Retry に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Retry
        {
            get
            {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }

        /// <summary>
        ///   Sea Shader に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SeaShader
        {
            get
            {
                return ResourceManager.GetString("SeaShader", resourceCulture);
            }
        }

        /// <summary>
        ///   Server URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ServerURI
        {
            get
            {
                return ResourceManager.GetString("ServerURI", resourceCulture);
            }
        }

        /// <summary>
        ///   Your settings have been saved
        ///(The new settings are applied after
        ///the browser is restarted) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingMessage
        {
            get
            {
                return ResourceManager.GetString("SettingMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings
        {
            get
            {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Sky Shader に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SkyShader
        {
            get
            {
                return ResourceManager.GetString("SkyShader", resourceCulture);
            }
        }

        /// <summary>
        ///   Teleport に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Teleport
        {
            get
            {
                return ResourceManager.GetString("Teleport", resourceCulture);
            }
        }

        /// <summary>
        ///   UserFolder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserFolder
        {
            get
            {
                return ResourceManager.GetString("UserFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   is empty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationEmpty
        {
            get
            {
                return ResourceManager.GetString("ValidationEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   invalid character に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationInvalidChar
        {
            get
            {
                return ResourceManager.GetString("ValidationInvalidChar", resourceCulture);
            }
        }

        /// <summary>
        ///   Maximum lenght に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationMaxLength
        {
            get
            {
                return ResourceManager.GetString("ValidationMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   item is too long. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationOver
        {
            get
            {
                return ResourceManager.GetString("ValidationOver", resourceCulture);
            }
        }

        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Version
        {
            get
            {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }

        /// <summary>
        ///   Voice に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Voice
        {
            get
            {
                return ResourceManager.GetString("Voice", resourceCulture);
            }
        }

        /// <summary>
        ///   Please confirm that your system meets the System Requirements of 3Di Viewer &quot;Rei&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WarningGraphicCardCaption
        {
            get
            {
                return ResourceManager.GetString("WarningGraphicCardCaption", resourceCulture);
            }
        }

        /// <summary>
        ///   Your graphics card is currently not supported.
        ///You might encounter unexpected behaviour. Do you want to continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WarningGraphicCardMessage
        {
            get
            {
                return ResourceManager.GetString("WarningGraphicCardMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   The region does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WarningTeleportMessage
        {
            get
            {
                return ResourceManager.GetString("WarningTeleportMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   he callee is busy now. 
        ///Please try again later. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WarningVoiceBusyMessage
        {
            get
            {
                return ResourceManager.GetString("WarningVoiceBusyMessage", resourceCulture);
            }
        }
    }
}
